"""Make a real Open-Meteo request and document the source-check outcome.

Run from the FloodGuard repository root:
    python backend/check_open_meteo_source.py

The script records metadata only (not the full forecast series). It updates
`docs/DATA_SOURCES.md` with a generated source-check block and writes a detailed
Markdown report plus a machine-readable JSON summary. A failed request is
recorded as failed/incomplete and is never described as verified.
"""
from __future__ import annotations

import json
import math
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import httpx

ROOT = Path(__file__).resolve().parents[1]
DATA_SOURCES_PATH = ROOT / "docs" / "DATA_SOURCES.md"
REPORT_PATH = ROOT / "docs" / "OPEN_METEO_SOURCE_CHECK.md"
JSON_PATH = ROOT / "data" / "reference" / "open_meteo_source_check.json"

ENDPOINT = "https://api.open-meteo.com/v1/forecast"
# Representative central Mumbai point for this smoke test only; do not infer
# ward-level or street-level weather coverage from this single coordinate.
REQUESTED_LATITUDE = 19.0760
REQUESTED_LONGITUDE = 72.8777
PARAMS = {
    "latitude": REQUESTED_LATITUDE,
    "longitude": REQUESTED_LONGITUDE,
    "hourly": "precipitation",
    "forecast_days": 2,
    "timezone": "UTC",
}
TIMEOUT_SECONDS = 15.0
TERMS_REVIEW_DATE = "2026-10-09"
TERMS_URL = "https://open-meteo.com/en/terms"
PRICING_URL = "https://open-meteo.com/en/pricing"
DOCS_URL = "https://open-meteo.com/en/docs"
CC_BY_URL = "https://creativecommons.org/licenses/by/4.0/"
START_MARKER = "<!-- BEGIN OPEN-METEO SOURCE CHECK (generated by backend/check_open_meteo_source.py) -->"
END_MARKER = "<!-- END OPEN-METEO SOURCE CHECK -->"


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z")


def coordinate(value: Any) -> float | None:
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        return None
    result = float(value)
    return result if math.isfinite(result) else None


def validate_payload(payload: Any) -> tuple[list[str], list[str]]:
    """Return (validation_errors, valid_times) for required forecast fields."""
    errors: list[str] = []
    if not isinstance(payload, dict):
        return ["Response JSON root was not an object."], []

    returned_lat = coordinate(payload.get("latitude"))
    returned_lon = coordinate(payload.get("longitude"))
    if returned_lat is None or returned_lon is None:
        errors.append("Provider-returned latitude/longitude were missing or invalid.")

    returned_timezone = payload.get("timezone")
    if not isinstance(returned_timezone, str) or not returned_timezone:
        errors.append("Provider-returned timezone was missing or invalid.")
    elif returned_timezone not in {"UTC", "GMT"}:
        errors.append(f"Requested UTC; provider returned unexpected timezone {returned_timezone!r}.")

    hourly = payload.get("hourly")
    if not isinstance(hourly, dict):
        errors.append("Missing or invalid 'hourly' object.")
        return errors, []

    times = hourly.get("time")
    precipitation = hourly.get("precipitation")
    hourly_units = payload.get("hourly_units")
    units = hourly_units.get("precipitation") if isinstance(hourly_units, dict) else None

    if not isinstance(times, list) or not times or not all(isinstance(t, str) for t in times):
        errors.append("Hourly valid-time list was missing, empty, or malformed.")
        times = []
    if not isinstance(precipitation, list):
        errors.append("Hourly precipitation values were missing or malformed.")
        precipitation = []
    if len(times) != len(precipitation):
        errors.append("Hourly valid-time and precipitation arrays had different lengths.")
    if units != "mm":
        errors.append(f"Expected precipitation unit 'mm'; provider returned {units!r}.")

    if times:
        for timestamp in times:
            try:
                datetime.fromisoformat(timestamp.replace("Z", "+00:00"))
            except ValueError:
                errors.append(f"Malformed forecast valid time: {timestamp!r}.")
                break

    return errors, times


def fmt(value: Any) -> str:
    if value is None:
        return "not returned"
    return str(value)


def make_report(record: dict[str, Any]) -> str:
    outcome = record["outcome"]
    successful = outcome == "PASS"
    title_status = "PASS — endpoint response and expected fields validated" if successful else "FAILED / INCOMPLETE — source not fully verified"
    requested = record["requested_location"]
    returned = record.get("provider_location") or {}
    valid_times = record.get("forecast_valid_times_utc", [])
    if valid_times:
        valid_coverage = (
            f"- **Forecast valid-time coverage:** `{valid_times[0]}` through `{valid_times[-1]}`\n"
            f"- **Valid-time count / cadence:** {len(valid_times)} timestamps; requested hourly data over two forecast days.\n"
        )
        all_times = ", ".join(f"`{x}`" for x in valid_times)
    else:
        valid_coverage = "- **Forecast valid-time coverage:** unavailable; no valid times were returned.\n- **Valid-time count / cadence:** 0 returned.\n"
        all_times = "None returned."

    validation = "No required-field validation errors." if not record.get("validation_errors") else "\n".join(
        f"- {error}" for error in record["validation_errors"]
    )
    errors = record.get("error_details") or "None reported."

    return f"""# Open-Meteo Real Request Source Check

**Outcome: {title_status}**

- **Date checked:** {record['date_checked']} (UTC)
- **Retrieval started:** `{record['retrieval_started_at_utc']}`
- **Retrieval completed:** `{record['retrieval_completed_at_utc']}`
- **HTTP status:** {fmt(record.get('http_status'))}
- **Request outcome:** {record['outcome_detail']}
- **Validation:** {validation}
- **Endpoint:** `{ENDPOINT}`
- **Exact request URL:** `{fmt(record.get('request_url'))}`
- **Requested parameters:** `hourly=precipitation`, `forecast_days=2`, `timezone=UTC`
- **Requested coordinates:** latitude `{requested['latitude']}`, longitude `{requested['longitude']}`
- **Provider-returned coordinates:** latitude `{fmt(returned.get('latitude'))}`, longitude `{fmt(returned.get('longitude'))}`
- **Returned elevation:** `{fmt(returned.get('elevation_m'))}` metres (where supplied)
- **Precipitation units:** requested/expected `mm`; provider returned `{fmt(record.get('precipitation_unit'))}`
- **Timezone:** requested `UTC`; provider returned `{fmt(record.get('timezone'))}` (abbreviation `{fmt(record.get('timezone_abbreviation'))}`, UTC offset seconds `{fmt(record.get('utc_offset_seconds'))}`)
{valid_coverage}- **All returned valid times (UTC):** {all_times}
- **Weather data type:** forecast/model output, not direct rain-gauge observations.
- **Representative location note:** the single point `{requested['latitude']}, {requested['longitude']}` is used only for this smoke test; it does not establish ward-level or street-level coverage.

## Usage terms and attribution

Official documentation: {DOCS_URL}

Terms and pricing pages reviewed on **{TERMS_REVIEW_DATE}**: {TERMS_URL} and {PRICING_URL}. The free API is for non-commercial use, subject to provider limits, and does not provide an uptime guarantee. Weather data is licensed under CC BY 4.0; provide appropriate credit and a link to the licence. Suggested visible attribution: **Weather data by Open-Meteo.com** ({"https://open-meteo.com/"}). Re-check the current terms before public deployment or any commercial use.

Licence: {CC_BY_URL}

## Limitations

A successful HTTP/schema check verifies only that this request returned the expected response structure and metadata at the recorded time. It does **not** validate forecast accuracy, model skill, future uptime, local rain-gauge agreement, flood prediction, or the suitability of one coordinate for every Mumbai ward. Open-Meteo may return a nearby model-grid coordinate rather than exactly the requested point. Precipitation is not proof of flooding or waterlogging.

## Error details

{errors}
"""


def make_datasources_block(record: dict[str, Any]) -> str:
    status = record["outcome"]
    if status == "PASS":
        summary = "Endpoint access and required response fields passed a single real-request smoke check. Forecast accuracy, geographic suitability, and sustained reliability remain unvalidated."
    else:
        summary = f"A real request was attempted but did not fully pass validation. Do not mark Open-Meteo as source-verified. Outcome: {record['outcome_detail']}"

    requested = record["requested_location"]
    provider = record.get("provider_location") or {}
    times = record.get("forecast_valid_times_utc", [])
    coverage = f"`{times[0]}` through `{times[-1]}` ({len(times)} hourly timestamps)" if times else "unavailable; no valid timestamps returned"
    errors = "; ".join(record.get("validation_errors", [])) or record.get("error_details") or "none"
    return f"""{START_MARKER}
### Real request source-check record — checked {record['date_checked']}

- **Result:** {status} — {summary}
- **Retrieval timestamps (UTC):** start `{record['retrieval_started_at_utc']}`; completion `{record['retrieval_completed_at_utc']}`
- **Endpoint:** `{ENDPOINT}`; HTTP status: `{fmt(record.get('http_status'))}`
- **Exact request URL:** `{fmt(record.get('request_url'))}`
- **Request parameters:** `latitude={requested['latitude']}`, `longitude={requested['longitude']}`, `hourly=precipitation`, `forecast_days=2`, `timezone=UTC`
- **Provider-returned coordinates:** latitude `{fmt(provider.get('latitude'))}`, longitude `{fmt(provider.get('longitude'))}`, elevation `{fmt(provider.get('elevation_m'))}` metres where supplied
- **Precipitation unit:** `{fmt(record.get('precipitation_unit'))}` (expected `mm`)
- **Timezone:** requested `UTC`; returned `{fmt(record.get('timezone'))}`; abbreviation `{fmt(record.get('timezone_abbreviation'))}`; UTC offset `{fmt(record.get('utc_offset_seconds'))}` seconds
- **Forecast valid times:** {coverage}
- **Outcome details / validation issues:** {errors}
- **Detailed report:** [`OPEN_METEO_SOURCE_CHECK.md`](OPEN_METEO_SOURCE_CHECK.md); machine-readable metadata: [`open_meteo_source_check.json`](../data/reference/open_meteo_source_check.json)
- **Terms checked:** {TERMS_REVIEW_DATE}; free API is for non-commercial use subject to limits; no uptime guarantee; data under [CC BY 4.0]({CC_BY_URL}); provide visible credit such as [Weather data by Open-Meteo.com](https://open-meteo.com/). Re-check current terms before public deployment or commercial use.
- **Limitations:** This is a single-point endpoint/payload smoke check, not a validation of forecast accuracy, live observations, ward-level coverage, or flood-prediction performance. Returned model-grid coordinates may differ from requested coordinates.
{END_MARKER}"""


def update_docs(record: dict[str, Any]) -> None:
    DATA_SOURCES_PATH.parent.mkdir(parents=True, exist_ok=True)
    if DATA_SOURCES_PATH.exists():
        text = DATA_SOURCES_PATH.read_text(encoding="utf-8")
    else:
        raise FileNotFoundError(f"Could not find expected project documentation: {DATA_SOURCES_PATH}")

    block = make_datasources_block(record)
    if START_MARKER in text and END_MARKER in text:
        pattern = re.escape(START_MARKER) + r".*?" + re.escape(END_MARKER)
        text = re.sub(pattern, lambda _: block, text, count=1, flags=re.DOTALL)
    else:
        anchor = "### Critical interpretation limits"
        if anchor in text:
            text = text.replace(anchor, block + "\n\n" + anchor, 1)
        else:
            text = text.rstrip() + "\n\n" + block + "\n"

    if record["outcome"] == "PASS":
        decision = "**Decision:** The endpoint and required response fields passed a single live-request smoke check on " + record["date_checked"] + "; forecast accuracy, geographic suitability, and sustained reliability are not validated."
    else:
        detail = record["outcome_detail"].replace("\n", " ")
        decision = "**Decision:** A live request was attempted on " + record["date_checked"] + " but was not fully validated (" + detail + "). Open-Meteo remains unverified; see the source-check record below."

    text = re.sub(r"^\*\*Decision:\*\*.*$", lambda _: decision, text, count=1, flags=re.MULTILINE)
    text = text.replace(
        "- [ ] Test one real Open-Meteo request from the Python backend.",
        "- [x] Attempted one real Open-Meteo request from the Python backend; recorded the actual outcome in the source-check entry.",
        1,
    )
    DATA_SOURCES_PATH.write_text(text.rstrip() + "\n", encoding="utf-8")


def main() -> int:
    started = utc_now()
    request_url: str | None = None
    http_status: int | None = None
    payload: Any = None
    unit: Any = None
    timezone_value: Any = None
    timezone_abbreviation: Any = None
    utc_offset_seconds: Any = None
    provider_location: dict[str, Any] = {}
    valid_times: list[str] = []
    validation_errors: list[str] = []
    error_details: str | None = None

    try:
        with httpx.Client(timeout=TIMEOUT_SECONDS, follow_redirects=True) as client:
            response = client.get(ENDPOINT, params=PARAMS)
            request_url = str(response.request.url)
            http_status = response.status_code
            if not response.is_success:
                error_details = f"HTTP {response.status_code}: {response.text[:500]}"
            else:
                try:
                    payload = response.json()
                except (ValueError, UnicodeError) as exc:
                    error_details = f"Response was not valid JSON: {type(exc).__name__}: {exc}"
    except httpx.TimeoutException as exc:
        error_details = f"Request timed out after {TIMEOUT_SECONDS:g} seconds: {type(exc).__name__}: {exc}"
    except httpx.RequestError as exc:
        error_details = f"Network/request error: {type(exc).__name__}: {exc}"
    except Exception as exc:  # Include unexpected failures in the audit log rather than claiming success.
        error_details = f"Unexpected check error: {type(exc).__name__}: {exc}"

    completed = utc_now()
    if error_details is None:
        validation_errors, valid_times = validate_payload(payload)
        if isinstance(payload, dict):
            provider_location = {
                "latitude": coordinate(payload.get("latitude")),
                "longitude": coordinate(payload.get("longitude")),
                "elevation_m": payload.get("elevation"),
            }
            timezone_value = payload.get("timezone")
            timezone_abbreviation = payload.get("timezone_abbreviation")
            utc_offset_seconds = payload.get("utc_offset_seconds")
            hourly_units = payload.get("hourly_units")
            unit = hourly_units.get("precipitation") if isinstance(hourly_units, dict) else None

    if error_details is not None:
        outcome = "FAILED"
        outcome_detail = error_details
    elif validation_errors:
        outcome = "INCOMPLETE"
        outcome_detail = "HTTP request succeeded, but one or more required fields failed validation."
    else:
        outcome = "PASS"
        outcome_detail = "HTTP request succeeded and required coordinates, timezone, hourly time series, and precipitation units validated."

    record: dict[str, Any] = {
        "source": "Open-Meteo Forecast API",
        "date_checked": completed[:10],
        "retrieval_started_at_utc": started,
        "retrieval_completed_at_utc": completed,
        "endpoint": ENDPOINT,
        "request_url": request_url,
        "request_parameters": PARAMS,
        "requested_location": {"latitude": REQUESTED_LATITUDE, "longitude": REQUESTED_LONGITUDE},
        "provider_location": provider_location,
        "http_status": http_status,
        "timezone": timezone_value,
        "timezone_abbreviation": timezone_abbreviation,
        "utc_offset_seconds": utc_offset_seconds,
        "precipitation_unit": unit,
        "forecast_valid_times_utc": valid_times,
        "forecast_valid_time_count": len(valid_times),
        "outcome": outcome,
        "outcome_detail": outcome_detail,
        "validation_errors": validation_errors,
        "error_details": error_details,
        "terms_review_date": TERMS_REVIEW_DATE,
        "terms_url": TERMS_URL,
        "pricing_url": PRICING_URL,
        "license_url": CC_BY_URL,
    }

    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    JSON_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(make_report(record), encoding="utf-8")
    JSON_PATH.write_text(json.dumps(record, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    update_docs(record)

    print(f"Open-Meteo source check: {outcome}")
    print(f"HTTP status: {fmt(http_status)}")
    print(f"Outcome: {outcome_detail}")
    if validation_errors:
        print("Validation issues:")
        for error in validation_errors:
            print(f"  - {error}")
    print(f"Report written: {REPORT_PATH.relative_to(ROOT)}")
    print(f"DATA_SOURCES updated: {DATA_SOURCES_PATH.relative_to(ROOT)}")
    print(f"JSON metadata written: {JSON_PATH.relative_to(ROOT)}")
    return 0 if outcome == "PASS" else 1


if __name__ == "__main__":
    sys.exit(main())
